### ISSUE TITLE
Can only calibrate 0.05 exposure times with firmware resin calibration tool? 

### ISSUE THREAD

**Issue by mylife4aiurr** [prusa3d/Original-Prusa-SL1#4]
I'd like to be able to use the new resin calibration tool to find layer exposure times for all supported layer heights..... Currently it looks like only 0.05 is supported in firmware?

**Comment by mylife4aiurr** [comment]
Any progress on this?

**Comment by SystemsGuy** [comment]
Please consider this another request to add layer height to the adjustable variables on the calibration prints.

**Comment by JakoobCZ** [comment]
> Please consider this another request to add layer height to the adjustable variables on the calibration prints.

We are working on more advanced calibration methods, including using your own objects. No ETA for now, but it should be out within several weeks.

**Comment by JakoobCZ** [comment]
> Any progress on this?

Hi,
we have added calibration objects for different layer heights [0.1mm, 0.05mm, 0.035mm, 0.025mm]. In order to get them, please head to Settings --> Advanced Settings and select Download Examples.

The entire process is described in a detail here: https://help.prusa3d.com/en/article/sl1-resin-calibration-object_112182
